# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15d202e3c6903e096320e84867737a36e4344ed0860873534de6a5592bf69102edaae0bf66f1e2646260aada597dfe4d6028799df78498cdf4bccd3cfcc33b50

test:
  secret_key_base: ed1156255cff3435f6534684d10148e4e1737f9db62be86dd3784d403275e6c3b7eb08b900490fe4de021f6f32b8ee4d0719f202c1ef870598ad985d204c45cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
